### ISSUE TITLE
Issues in Catalina....

### ISSUE THREAD

**Issue by ehossain1982** [mwang87/q2_metabolomics#51]
I installed it and it went well. But it does not show up in as an qiime2 option. If I try the code , it does not work. But if I try to reinstall it says the plugin is already installed. I am in OS X Catalina and QIIME2 env. How do I fix this? Thank you.

**Comment by mwang87** [comment]
We currently have tested on ubuntu 18.04 for qiime 18.06 as outlined in our README.md. We do not have a OS X Catalina system to test on. 

If you would to help fix this issue, please put in the exact commands and errors and system description. 

Thanks!

**Comment by ehossain1982** [comment]
Here is a screen shot of the installation process: https://imgur.com/HyYZuXS

It also has the results of "qiime" command. 

My sytem info: 2019 16" MacBook Pro with Catalina 10.15.2 (Mac OSX) and i9. 

On a different note: the last post on this thread is the identical error as I encountered.

https://forum.qiime2.org/t/cant-find-q2-metabolomics-plugin/12946/5

Thanks.

**Comment by mwang87** [comment]
We current are not supporting the conda installation and recommend pip. Additionally, we further recommend you simply run in GNPS and not on commandline since its easier to get a qza file that way.
